### ISSUE TITLE
add CI integration with Circle CI

### ISSUE THREAD

**Issue by PlayMa256** [PlayMa256/node-modules-analyzer#11]
This is to add ci steps onto each commit!!

**Comment by jgcmarins** [comment]
What about GH actions?

**Comment by PlayMa256** [comment]
> What about GH actions?

That aswell! I just forgot to add an issue about it hahaha

**Comment by PlayMa256** [comment]
ps: added integration for packages with circle ci. For using this module with circle ci it can be used as a linter!
