### ISSUE TITLE
add README.md to root

### ISSUE THREAD

**Issue by jgcmarins** [PlayMa256/node-modules-analyzer#14]
Hi

I guess this happened because you moved it into `cli` package, but there's no `README.md` on the root:
<img width="1026" alt="Screen Shot 2020-06-01 at 11 33 13" src="https://user-images.githubusercontent.com/5133450/83419696-dbebbd80-a3fb-11ea-8dc2-de3311dac0c9.png">
<img width="1031" alt="Screen Shot 2020-06-01 at 11 33 32" src="https://user-images.githubusercontent.com/5133450/83419704-dee6ae00-a3fb-11ea-9069-27855b09c3f3.png">

**Comment by PlayMa256** [comment]
Yes! I have to write a better readme (which I did not have time for)! Thank you! <3

**Comment by PlayMa256** [comment]
closed on ddcd81fac0441954285977b5091121a20ab8ad76
