### ISSUE TITLE
Exit with non 0 when problems found

### ISSUE THREAD

**Issue by TrySound** [PlayMa256/node-modules-analyzer#21]
.yarnclean is able to eliminate all problems. Btw is there something similar in npm?
node-modules-analyzer can be used as linter in CI. Similar works `prettier --lint-different` when 
not formatted files found.

## Expected Behavior

Exit with non null status code

## Current Behavior

Exit with null.

## Your Environment

- Library Version used: 1.1.0
- Node.js version (e.g. Node.js 5.4): 13.12
- Operating System and version (desktop or mobile): mac os

**Comment by PlayMa256** [comment]
released on `1.2.2`
