### ISSUE TITLE
Allow only one variant of license or changelog in package.

### ISSUE THREAD

**Issue by TrySound** [PlayMa256/node-modules-analyzer#27]
License and changelog are always included. Analyzer can check that only one instance is present in package.
![image](https://user-images.githubusercontent.com/5635476/83976042-1a9fdd00-a900-11ea-9adf-a14c247fe208.png)

**Comment by PlayMa256** [comment]
For licenses, maybe reporting as
`LICENSE*` => where * may be any other extension?

I'm not quite sure how we could tell the user that are more than one instance, for both cases!

Any ideas?

**Comment by TrySound** [comment]
Yeah, probably the first is the winner

**Comment by PlayMa256** [comment]
fixed on #33 
released on 1.3.0 (core + cli)
